# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2020 South East Open Source Solutions Ltd.
#		     Tim Small <tim@seoss.co.uk>

obj-y += cubemb1.o
obj-y += ../../atmel/common/board.o
obj-$(CONFIG_I2C_EEPROM) += ../../atmel/common/mac_eeprom.o
